export enum Module {
  ADMIN = 'ADMIN',
  ACCOUNT = 'ACCOUNT',
  USER = 'USER',
  LOAN = 'LOAN',
  SAVINGS = 'SAVINGS',
  SHARES = 'SHARES',
  SYSTEM = 'SYSTEM',
  REPORTS = 'REPORTS',
  TRANSACTION = 'TRANSACTION'
}

export enum Action {
  CREATE = 'CREATE',
  READ = 'READ',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  APPROVE = 'APPROVE',
  REVIEW = 'REVIEW',
  VERIFY = 'VERIFY',
  MANAGE = 'MANAGE',
  DISBURSE = 'DISBURSE',
  WITHDRAW = 'WITHDRAW',
  REQUEST = 'REQUEST'
}
